gems:
  - jekyll-redirect-from
theme: jekyll-theme-slate
title: RED - Robot Editor
description: Eclipse based editor for RobotFramework testcases
show_downloads: false
redirect_from: "http://polusaleksandra.github.io/red/"
relative_links:
  enabled: true
  collections: true